name: Test and lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  TARGETS: memrise_audio_uploader tests

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run pylint
        run: make pylint

      - name: Run isort
        run: make isort

      - name: Run black
        run: make black

      - name: Run tests
        run: make test
